In [49]:
import numpy as np
import open3d as o3d
import os
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm_notebook

In [50]:
%matplotlib notebook

In [192]:
BASE_PATH = "/home/saby/Projects/ati/data/data/datasets/Carla/64beam-Data/pair_transform_dynseg_all/segmentation_preprocess/"
DYNAMIC_FOLDER = "static_preprocessed"
MASK_FOLDER = "static_mask_npy"
# STATIC_FOLDER = "static_preprocessed"

DYNAMIC_PATH = "/home/saby/Projects/abhinav/transfer/ply_with_noise_new_0.5_out_npy/0.npy"#os.path.join(BASE_PATH, DYNAMIC_FOLDER, "15.npy")
# MASK_PATH = "/home/saby/Projects/abhinav/transfer/carla_noisy_dyn1/0.05.npy"#os.path.join(BASE_PATH, MASK_FOLDER, "15.npy")
# STATIC_PATH = os.path.join(BASE_PATH, STATIC_FOLDER, "15.npy")

In [193]:
dynamic_arr = np.load(DYNAMIC_PATH)
# mask_arr    = np.load(MASK_PATH)

In [194]:
dynamic_arr.shape, mask_arr.shape

((1275, 64, 1024, 4), (984, 64, 1024, 4))

In [195]:
pd.DataFrame(dynamic_arr[10,0].reshape(1,-1)[0]).describe()

0
count  4096.000000
mean     -2.718369
std      27.451438
min    -120.301132
25%      -3.282597
50%       0.000000
75%       1.251246
max     108.708786

In [200]:
(dynamic_arr[-1] == 0).sum()

68671

In [197]:
(dynamic_arr[10,1] == 0).sum()

1025

In [198]:
print(dynamic_arr)

[[[[ 2.40344200e+01  0.00000000e+00 -1.12562478e+00  0.00000000e+00]
   [ 2.95185757e+01  1.81303039e-01 -5.84764123e-01  0.00000000e+00]
   [ 3.61318398e+01  4.43860143e-01  2.37364101e+00  0.00000000e+00]
   ...
   [ 1.71970024e+01 -2.11255908e-01 -1.93544161e+00  0.00000000e+00]
   [ 1.58317957e+01 -9.72388610e-02 -1.80339944e+00  0.00000000e+00]
   [ 2.40907898e+01 -5.90054205e-15 -7.99883366e-01  0.00000000e+00]]

  [[ 4.15171242e+01  0.00000000e+00 -1.82551014e+00  0.00000000e+00]
   [ 2.56385155e+01  1.57471716e-01 -1.47481072e+00  0.00000000e+00]
   [ 1.20130386e+01  1.47573695e-01 -1.66003537e+00  0.00000000e+00]
   ...
   [ 1.19885759e+01 -1.47273183e-01  1.71990216e+00  0.00000000e+00]
   [ 2.80973225e+01 -1.72573715e-01  3.82430643e-01  0.00000000e+00]
   [ 7.27848911e+00 -1.78271573e-15 -2.21894097e+00  0.00000000e+00]]

  [[ 3.34817772e+01  0.00000000e+00  1.80949962e+00  0.00000000e+00]
   [ 2.79060936e+01  1.71399191e-01 -2.42577696e+00  0.00000000e+00]
   [ 1.31078186e