In [1]:
import pandas as pd
import numpy as np
import open3d as o3d

In [58]:
pcd = o3d.io.read_point_cloud("/home/sabyasachi/Projects/ati/data/data/datasets/Carla/16beam-Data/static_fullmap_autopilot/_out/1.ply")

In [59]:
pcd

geometry::PointCloud with 18042 points.

In [60]:
arr = np.asarray(pcd.points)
arr

array([[ 2.872e+01, -6.336e+01, -1.864e+01],
       [ 2.894e+01, -6.327e+01, -1.864e+01],
       [ 2.915e+01, -6.318e+01, -1.865e+01],
       ...,
       [-1.400e-01, -1.426e+01,  3.820e+00],
       [-1.000e-01, -1.426e+01,  3.820e+00],
       [-5.000e-02, -1.426e+01,  3.820e+00]])

In [61]:
desired_size = 1000
what_size = min(desired_size, arr.shape[0])
idx = np.random.choice(arr.shape[0], size=what_size, replace=False)
idx

array([ 1476,  3195,  5250, 11424, 11686,  2129,  5720,   271, 11897,
         736,  6259,  6470, 17040,  3037,  7602,  5560, 11617,  4825,
        8518, 12844, 15789, 12276,  3319,  5696,  3136, 15436, 17057,
       17357,  3536, 10095,  4841, 10599,  1115, 12785,  3140,  9282,
        5192,  6663,  5756,  4181,  4861,  1159, 14680,  1385, 13036,
        9671, 15690,  4884, 15837, 16046,  8873,  7219,   770, 13752,
       13481, 13990, 11004,  9478, 10308, 14195, 13294,   754,  3908,
        6798, 17892,  5057, 10823,  7422,  6732,   426,  6052,   826,
       14602,  2178,  1774,  8057,  5982,  9334, 17212, 10921,  8787,
       10756,  5023, 11810, 10542,  8869,  3660,  1245, 14573,  7631,
        3762,  9752, 10170,  8694, 15077, 16959,  4729, 17208,  7442,
       11381, 17227,  4178,  2530,  7423,  7251, 15094,  8546,  1804,
       12792, 11666,  4430,  8808,  4771, 14836, 10780,  7838, 14114,
       14524,  3390, 15170,  3780,  5968, 15448, 14188,  2344,   318,
        3115,  2634,

In [62]:
idx.shape

(1000,)

In [21]:
arr[idx]

array([[  5.53,   0.67,  -1.29],
       [  5.7 ,  -7.7 ,  -0.82],
       [  5.7 ,  -4.06,   0.37],
       [-10.22,   5.86,   1.85],
       [  5.7 ,  -2.76,   1.7 ],
       [  2.38,  12.18,   2.39],
       [-10.22,  -2.25,   2.04],
       [  5.54,  -4.2 ,   0.62],
       [ 62.93,  19.86,  -5.81],
       [-10.22,  -5.17,  -0.19]])

In [25]:
pcd.points = o3d.utility.Vector3dVector(arr[idx])

In [28]:
o3d.io.write_point_cloud("fraction_of_7000.ply", pcd, write_ascii=True)

True